#!/bin/bash
HISTFILE=""

setopt hist_ignore_all_dups

zstyle :compinstall filename '/home/Raj/.zshrc'
autoload -Uz compinit
compinit

### My Aliases
alias ip="ip --color=auto"
alias ls="eza --color=always --icons=always --octal-permissions --binary --across"
alias l="eza --long --color=always --icons=always --group --octal-permissions --binary --across"
alias la="eza --color=always --icons=always --group --octal-permissions --binary --across --almost-all"
alias ll="eza --long --color=always --icons=always --group --long --header --classify=always --octal-permissions --binary --across --total-size"
alias lll="eza --long --color=always --icons=always --group --numeric --long --header --classify=always --octal-permissions --binary --across --total-size"
alias diff="diff --color=auto"
alias bat="bat --color=always --decorations=never"
alias catbat="bat --color=always --decorations=never --paging=never"
alias batnp="bat --color=always --paging=never --decorations=never"
alias batdecl="bat --color=always --paging=never --decorations=always"
alias batCD="clear; bat --paging=never --decorations=never"
alias grep="grep --color=auto"
alias dir="dir --color=auto"
alias MOD="rclone mount OneDrive:/ /home/Raj/OneDrive/ --daemon"
alias UOD="sudo umount /home/Raj/OneDrive/ --force"
alias ncdu="ncdu --color dark"
alias ncduc="clear; ncdu --color dark"
alias qemu="qemu-system-x86_64"
alias firefox-dev="firefox-developer-edition"
alias firefoxdev="firefox-developer-edition"
alias sways="clear; sway --unsupported-gpu 1> /dev/null 2>&1"
alias VimBeGood="clear; docker run -it --rm brandoncc/vim-be-good:stable && echo && clear"
alias CppDir="cd ~/DEV/GitRepos/C++/"
alias sourceme="source ~/.zshrc.pre-oh-my-zsh"
alias zshrc="clear; vim ~/.zshrc"
alias vimrc="clear; vim ~/.vimrc"
alias nvimrc="clear; nvim ~/.config/nvim/init.vim"
alias yazi="EDITOR=nvim yazi"
alias yazic="clear; EDITOR=nvim yazi"
alias vimc="clear; vim"
alias nvimc="clear; nvim"
alias btopc="clear; btop"
alias y="yazi"
alias gtypistH="gtypist --personal-best --max-error=1.8 --no-welcome-screen --term-cursor --word-processor --always-sure"
alias not_needed_pkg="pacman -Qtdq"
alias clearcache="sudo pacman -Scc && yay -Scc"
alias weather="curl wttr.in/24.5800,80.8369"
alias diff="colordiff"
alias feh="imv"
alias nvtop="nvtop --delay 2"
alias gs="git status"
alias SystemFont_list="fc-list | awk -F':' '{print $1}' | awk -F'/' '{print $6}' | awk -F'.' '{print $1}' | sort -u"

### Flatpak Applications
alias scrivano="flatpak run com.github.scrivanolabs.scrivano"
alias draw="flatpak run com.github.scrivanolabs.scrivano"
alias tipp10="flatpak run com.gitlab.tipp10.tipp10"
alias ktouch="flatpak run org.kde.ktouch"
alias typing="flatpak run org.kde.ktouch"
alias easyeffects="flatpak run com.github.wwmm.easyeffects"
alias effects="flatpak run com.github.wwmm.easyeffects"
alias zen="flatpak run app.zen_browser.zen"
alias pomodoro="flatpak run org.jousse.vincent.Pomodorolm"
alias pomodorolm="flatpak run org.jousse.vincent.Pomodorolm"
alias discord="flatpak run com.discordapp.Discord"
alias VideoEditor="flatpak run org.kde.kdenlive 2> /dev/null"
alias calculator="flatpak run io.github.Qalculate.qalculate-qt"
alias qcal="flatpak run io.github.Qalculate.qalculate-qt"

export WINEPREFIX="$HOME/wine"
export PATH="$PATH:$HOME/.path/scripts:$HOME/.path/exercism"

function Tor_proxy() {
    u_set="{$1:-"NULL"}"
    if [[ $u_set == "unset" ]]; then
        unset http_proxy
        unset https_proxy
        exit 0
    fi
    export http_proxy="socks5://127.0.0.1:9050"
    export https_proxy="socks5://127.0.0.1:9050"

}

function encode() {
    local input="$1"
    local should_save="$2"
    local output_file_name="$3"

    if [[ -d "$input" ]]; then
        echo "We don't accept directories"
    elif [[ -f "$input" ]]; then
        echo "This is the file: $input"
        [[ $should_save == "true" ]] && { cat "$input" | tr "A-Za-z" "N-ZA-Mn-za-m" > "$output_file_name"; } || \
            { cat "$input" | tr "A-Za-z" "N-ZA-Mn-za-m"; }
        else
            [[ $should_save == "true" ]] && { echo "$input" | tr "N-ZA-Mn-za-m" "A-Za-z" > "$output_file_name"; } || \
                { echo "$input" | tr "N-ZA-Mn-za-m" "A-Za-z" ; }
    fi
}

function decode() {
    local input="$1"
    local should_save="$2"
    local output_file_name="$3"

    if [[ -d "$input" ]]; then
        echo "We don't accept directories"
    elif [[ -f "$input" ]]; then
        echo "This is the file: $input"
        [[ $should_save == "true" ]] && { cat "$input" | tr "N-ZA-Mn-za-m" "A-Za-z" > "$output_file_name"; } || \
            { cat "$input" | tr "N-ZA-Mn-za-m" "A-Za-z" ; }
    else
        [[ $should_save == "true" ]] && { echo "$input" | tr "N-ZA-Mn-za-m" "A-Za-z" > "$output_file_name"; } || \
            { echo "$input" | tr "N-ZA-Mn-za-m" "A-Za-z" ; }
    fi
}

function rot13() {
    local operation="$1"
    local input="$2"
    local should_save="$3"
    local output_file="$4"

    [[ $should_save == "-s" ]] && should_save="true" || should_save="false"

    if [[ $# -gt 1 ]]; then
        if [[ ! -f "$input" ]]; then
            echo "Only file and Strings are allowed"
        else
            if [[ $operation =~ ^(encode|e|-e)$ ]]; then
                encode "$input" "$should_save" "$output_file"
            elif [[ $operation =~ ^(decode|d|-d)$ ]]; then
                decode "$input" "$should_save" "$output_file"
            fi
        fi
    else
        echo "[ERROR]: At least two arguments expected"
        echo "rot13 <encode/decode> <file/string>"
    fi
}

function Pretty() {
    for file in "$@"; do
        echo "$file" |  sed 's/[^A-Za-z0-9._-]/_/g' | sed 's/_\+/_/g' 2> /dev/null
    done
}

function Pretty_rename() {
    for file in "$@"; do
        mv -- "${file}" "$(echo "$file" | sed 's/\[[^]]*\]//g' | sed 's/[^A-Za-z0-9._-]/_/g' | sed 's/_\+/_/g')" 2> /dev/null
    done
}

function Extract() {
    local archive="$1"

    if [[ "${archive}" == *.tar  ]]; then
        tar --extract --verbose --file="${archive}"
    elif [[ "${archive}" == *.tar.gz  ]]; then
        tar --extract --gzip --verbose --file="${archive}"
    elif [[ "${archive}" == *.tar.xz  ]]; then
        tar --extract --xz --verbose --file="${archive}"
    elif [[ "${archive}" == *.tar.bzip2  ]]; then
        tar --extract --bzip2 --verbose --file="${archive}"
    else
        printf "Sorry this is not tar archieve"
    fi
}

function CompileC() {
    local file="$1"
    gcc -pedantic -Wall -Wextra "$file" -o "${file%%.*}" && ./"${file%%.*}"
}

function CompileCPP() {
    local file="$1"
    g++ -pedantic -std=c++14 -fno-elide-constructors -Wall -Wextra "$file" -o "${file%%.*}" && ./"${file%%.*}"
}

function Compile_C() {
    local file="$1"
    clang -pedantic -Wall -Wextra "$file" -o "${file%%.*}" && ./"${file%%.*}"
}

function Compile_CPP() {
    local file="$1"
    clang++ -pedantic -Wall -Wextra "$file" -o "${file%%.*}" && ./"${file%%.*}"
}

function Yt-dlp_download() {
    local url="$@"
    yt-dlp -f "bestvideo[height<=1080]+bestaudio/audio[height<=1080]" "$url"
}

function Steam() {
    DRI_PRIME=1 __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only __GLX_VENDOR_LIBRARY_NAME=nvidia steam
}

function Update-grub() {
    sudo grub-mkconfig -o /boot/grub/grub.cfg
}

function vim() {
    local FILE="$@"
    case "${FILE##*.}" in
        cpp|c++|c|py)
            /usr/bin/nvim "$FILE"
            ;;
        *)
            /usr/bin/vim "$FILE"
            ;;
    esac
}

function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

function yc() {
    clear
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    if cwd="$(command cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
        builtin cd -- "$cwd"
    fi
    rm -f -- "$tmp"
}

